name: make
on: [push]
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run:  sudo apt update
      - run:  curl --silent -L https://github.com/bio-guoda/preston/releases/download/0.11.8/preston.deb > preston.deb && sudo apt install -q ./preston.deb
      - run: sudo apt install -q jq miller
      - name: build
        run: make
      - name: review report archive
        uses: actions/upload-artifact@v7
        with:
          name: traitbank
          path: |
            data/**
            dist/*
            HEAD
            README.md
            Makefile
            *.jq
      - name: trait.tsv
        uses: actions/upload-artifact@v7
        with:
          path: dist/trait.tsv
          archive: false
      - name: trait.json
        uses: actions/upload-artifact@v7
        with:
          path: dist/trait.json
          archive: false
